name: build-and-push-meraki-beta-sdk
on:
  push:
    branches:
      - master

env:
  BOUNDLESS_ORG_ID: 849070


jobs:
  build-and-push-meraki-beta-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract commit SHA
        shell: bash
        run: echo '##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")'
        id: extract_version

      - name: Pull Upstream Changes
        run: |
          rm -rf meraki
          git config  user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config  user.name "github-actions[bot]"
          git pull  --rebase https://github.com/meraki/dashboard-api-python.git master

          git add .
          git commit 'upstream changes'

      - name: Building SDK
        run: |
          pip install -r requirements.txt
          rm -rf meraki
          cd generator
          python generate_library.py -o ${{ env.BOUNDLESS_ORG_ID}} -k ${{ secrets.MERAKI_DASHBOARD_API_KEY_BOUNDLESS }}

          mv meraki ../
          cd ..

      - name: Commit files
        run: |
          git config  user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config  user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publishing SDK done
        run: echo "Deployment of $(git rev-parse --verify HEAD) to ${{ env.BUILD_ENVIRONMENT }} finished at $(date)"